kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: guestbook
subjects:
  - kind: ServiceAccount
    name: guestbook-sa
    namespace: guestbook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
