kind: Deployment
apiVersion: apps/v1
metadata:
  name: guestbook-frontend
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/google-samples/gb-frontend:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: GET_HOSTS_FROM
            value: dns
          network_mode: host
          privileged: true
          user: root
