kind: Deployment
apiVersion: apps/v1
metadata:
  name: guestbook-frontend
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      serviceAccountName: guestbook-sa
      serviceAccount: guestbook-sa
      containers:
        - name: frontend
          #image: gcr.io/google-samples/gb-frontend:v6
          image: paulczar/gb-frontend:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
          - name: GET_HOSTS_FROM
            value: dns

