apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: guestbook-subscription
  namespace: guestbook
  labels:
    app: guestbook-app
  annotations:
    apps.open-cluster-management.io/git-path: apps/guestbook/
    apps.open-cluster-management.io/git-branch: stage
spec:
  channel: open-cluster-management/guestbook-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: guestbook-development-clusters
